### ISSUE TITLE
Epic Task: Add Changelog/Tagging deps/scripts to all derivitive OBE:WDS repos from this starter

### ISSUE THREAD

**Issue by oberocks** [obewds/vite-vue-ts-compo-pkg-starter#97]
# Epic Task: Add Changelog/Tagging deps/scripts to all derivative OBE:WDS repos from this starter

Have learned and tested out how to add automatic changelog logging and automated Git tagging (opening up release tags getting generated just after a publish to npm!

<br>

# Repos List as To-Do's

The above changes need to be done for the following repositories:

## Package Starter Kit Template (GitHub)

- [x] [vite-vue-ts-compo-pkg-starter](https://github.com/obewds/vite-vue-ts-compo-pkg-starter)

## Tailwind Defaults Packages (GitHub + NPM)

> From non-dependent packages to dependent packages - so update these in order when bumping versions!

- [x] [tw-bg-palette-console](https://github.com/obewds/tw-bg-palette-console)
- [x] [tw-bg-palette-default](https://github.com/obewds/tw-bg-palette-default)
- [x] [tw-bg-palette-monochromatic](https://github.com/obewds/tw-bg-palette-monochromatic)
- [x] [tw-bg-palette-pastel](https://github.com/obewds/tw-bg-palette-pastel)
- [x] [tw-border-palette-default](https://github.com/obewds/tw-border-palette-default)
- [x] [tw-text-palette-default](https://github.com/obewds/tw-text-palette-default)
- [x] [obewds-tw-config](https://github.com/obewds/obewds-tw-config)

## List of Utility Packages (GitHub + NPM)

> From non-dependent packages to dependent packages - so update these in order when bumping versions!

- [x] [vue-validators](https://github.com/obewds/vue-validators)
- [x] [vue-component-helpers](https://github.com/obewds/vue-component-helpers)

## Component Packages (GitHub + NPM)

> From non-dependent packages to dependent packages - so update these in order when bumping versions!

- [x] [vue-el](https://github.com/obewds/vue-el)
- [x] [vue-tw-el](https://github.com/obewds/vue-tw-el)
- [x] [vue-tw-block](https://github.com/obewds/vue-tw-block)
- [x] [vue-tw-inline](https://github.com/obewds/vue-tw-inline)

<br>

# Update Steps for Each Repo

To ripple this change out to all derivative OBE:WDS repos created from this starter kit, complete each of the following steps in each derivative repo:

### STEP 1

Install the following new dependency:

```bash
npm install auto-changelog --save-dev
```

### STEP 2

Change the following lines in the repo's `./package.json` file from this:

```json
{
  "scripts": {
    "publish:prep": "npx rimraf dist && npm run pkg:tsbundle",
    "publish:package": "npm run publish:prep && npm run pkg:org && npm run pkg:login && npm run pkg:publish",
  },
}
```

To this:

```json
{
  "scripts": {
    "changelog": "auto-changelog --package --unreleased --backfill-limit 20",
    "git:tag" : "PACKAGE_VERSION=$(cat package.json | grep \\\"version\\\" | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') && git tag v$PACKAGE_VERSION && git push --tags",
    "publish:prep": "npx rimraf dist && npm run pkg:tsbundle && npm run changelog",
    "publish:package": "npm run publish:prep && npm run pkg:org && npm run pkg:login && npm run pkg:publish && npm run git:tag && npm run changelog"
  },
}
```

### STEP 3

Open up the project's main `./README.md` file and add the following link underneath the link to the repo's GitHub docs site:

```bash
Or check out the [CHANGELOG](https://github.com/obewds/vite-vue-ts-compo-pkg-starter/blob/main/CHANGELOG.md) for the code base!
```

### STEP 4

It's never a bad idea to go ahead and do a dependency updates check using the following commands:

```bash
npm outdated
```

And then update outdated packages either manually by replacing outdated deps one-by-one, or all together with:
```bash
npm update
```

### STEP 5

And lastly, be sure to run a publish prep script to generate a new changelog:

```bash
npm run publish:prep
```

Or in the case of needing to go ahead and publish an update (for example if bumping dependencies while making these changes), then go ahead and run the `package:prep` script above and make a quick commit of the files for GitHub, and then make another final commit of the newest `./CHANGELOG.md` file generated after running the following script:

```bash
npm run publish:package
```

**Comment by oberocks** [comment]
all sub tasks completed
